### ISSUE TITLE
Putty fails with WinSock error

### ISSUE THREAD

**Issue by webmany** [Toyoyo/putty-win32s#1]
Running Win 3.11 with MS TCP/IP 3.11b installed.  When I try running the compiled version of putty 0.74 I get Unable to initialise WinSock.

I have winsock.dll version 3.11.160

**Comment by Toyoyo** [comment]
Could you check which version of win32s is installed?
I've been testing with 1.30c, which should have wsock32.dll version 1.30.172.

**Comment by webmany** [comment]
wsock32.dll is version 1.30.172

**Comment by Toyoyo** [comment]
I can't reproduce, including in my dosbox-x install.
Given what I see in winnet.c (basically, a call to p_WSAStartup()), I would suppose winsock is indeed not working.
Is TCP/IP really working properly?

**Comment by webmany** [comment]
It is working, I am able to use netscape and ping sites.it crashed   However, after saying that, it started working with no changes.  I did gun puttygen and tried generating a key, but it finished with out of thread resources.  After closing it and running putty, it worked fine.  I'll blame sunspots.
